-- Set up Warehouse
CREATE OR REPLACE WAREHOUSE COMPUTE_LOADING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE COMPUTE_TRANSFORM WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE;

CREATE OR REPLACE WAREHOUSE COMPUTE_BI WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 600 AUTO_RESUME = TRUE;

-- Set up Database
CREATE OR REPLACE DATABASE PublicTransportation;

-- set up table
CREATE OR REPLACE TABLE Public.DIM_BUS(
	bus_code int NOT NULL,
	number_of_seat int NOT NULL,
	type nvarchar(10) NOT NULL
);

CREATE OR REPLACE TABLE Public.DIM_BUSSTOP(
	bus_stop_id int NOT NULL,
    route_id int NOT NULL,
	name nvarchar(100) NOT NULL,
	street nvarchar(100) NOT NULL,
	district int NOT NULL,
    latitude float NOT NULL,
	longtitude float NOT NULL,
	arrival_time time(7) NULL
);

CREATE OR REPLACE TABLE Public.DIM_ROUTE(
	route_id int NOT NULL,
	agency_id int NOT NULL,
	route_name nvarchar(50) NOT NULL,
	departure_name nvarchar(50) NOT NULL,
	destination_name nvarchar(50) NOT NULL,
	duration int NOT NULL,
	fare int NOT NULL,
	frequency int NOT NULL,
	number_of_stop int NOT NULL,
	number_of_bus int NOT NULL,
	operating_hour_start time(7) NOT NULL,
	operating_hour_end time(7) NOT NULL,
	distance int NOT NULL
);

CREATE OR REPLACE TABLE Public.FACT_TRIP(
	trip_id int NOT NULL,
	bus_code int NOT NULL,
    bus_stop_id int NOT NULL,
    stop_time_id int NOT NULL,
    route_id int NOT NULL,
	trip_headsign nvarchar(150) NOT NULL,
    date_stop date NOT NULL,
	time_stop time(7) NOT NULL,
	number_of_ticket int NOT NULL
);

CREATE OR REPLACE TABLE Public.STAGE_BUSSTOP(
	bus_stop_id int NOT NULL,
	name nvarchar(100) NOT NULL,
	street nvarchar(100) NOT NULL,
	district int NOT NULL,
    latitude float NOT NULL,
	longtitude float NOT NULL
);

CREATE OR REPLACE TABLE Public.STAGE_TRIP(
	trip_id int NOT NULL,
	bus_code int NOT NULL,
	trip_headsign nvarchar(150) NOT NULL,
    date_stop date NOT NULL,
	time_stop time(7) NOT NULL,
	number_of_ticket int NOT NULL
);

CREATE OR REPLACE TABLE Public.STAGE_STOPROUTE(
	bus_stop_id int NULL,
	route_id int NULL,
	arrival_time time(7) NULL
);
  
CREATE OR REPLACE TABLE Public.STAGE_STOPTIME(
	stop_time_id int NOT NULL,
	trip_id int NOT NULL,
	bus_stop_id int NOT NULL
);

-- Create csv file format
CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
DATE_FORMAT = 'YYYY-MM-DD';

-- Create Stages
CREATE STAGE UPLOAD_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE STAGE UNLOAD_STAGE
FILE_FORMAT = CSV_FORMAT;

-- Create Tasks to load data from stage to tables in PublicTransportation DB
USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET TIMEZONE = 'Asia/Ho_Chi_Minh'

--- UPDATE DIM_BUSCALENDAR
CREATE OR REPLACE TASK add_BusCalendar
  WAREHOUSE = TRANSPORT_WH
    SCHEDULE = 'USING CRON 30 15 4 9 * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusCalendar TABLE'
AS
COPY INTO BUSCALENDAR_STAGE
FROM @UPLOAD_STAGE/BusCalendar_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSCALENDAR
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusCalendar
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSCALENDAR
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSCALENDAR_STAGE;

-- Task to truncate stage table BUSCALENDAR_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSCALENDAR_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSCALENDAR
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSCALENDAR_STAGE;

--- UPDATE DIM_BUSTYPE
CREATE OR REPLACE TASK add_BusType
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add Bustype TABLE'
AS  
COPY INTO BUSTYPE_STAGE
FROM @UPLOAD_STAGE/BusType_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSTYPE
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusType
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSTYPE
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSTYPE_STAGE;

-- Task to truncate stage table BUSTYPE_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSTYPE_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSTYPE
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSTYPE_STAGE;

-- UPDATE DIM_BUSROUTE
CREATE OR REPLACE TASK add_BusRoute
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusRoute TABLE'
AS
COPY INTO BUSROUTE_STAGE
FROM @UPLOAD_STAGE/BusRoute_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSROUTE
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusRoute
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSROUTE
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSROUTE_STAGE;

-- Task to truncate stage table BUSROUTE_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSROUTE_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSROUTE
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSROUTE_STAGE;

-- UPDATE DIM_BUSINFO
CREATE OR REPLACE TASK add_BusInfo
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusInfo TABLE'
AS
COPY INTO BUSINFO_STAGE
FROM @UPLOAD_STAGE/BusInfo_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSINFO
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusInfo
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSINFO
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSINFO_STAGE;
-- Task to truncate stage table BUSINFO_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSINFO_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSINFO
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSINFO_STAGE;

-- UPDATE FACT_BUSTRIP
CREATE OR REPLACE TASK add_BusTrip
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusTrip TABLE'
AS
COPY INTO BUSTRIP_STAGE
FROM @UPLOAD_STAGE/BusTrip_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_FACT_BUSTRIP
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusTrip
AS
  INSERT INTO WAREHOUSE_DB.PUBLIC.FACT_BUSTRIP
  SELECT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSTRIP_STAGE;

-- Task to truncate stage table BUSTRIP_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSTRIP_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_FACT_BUSTRIP
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSTRIP_STAGE;

CREATE OR REPLACE TASK remove_files_in_upload_stage
  WAREHOUSE = TRANSPORT_WH
  COMMENT = 'Remove files in upload stage'
  AFTER TRUNCATE_BUSTRIP_STAGE
AS
REMOVE @UPLOAD_STAGE;

CREATE OR REPLACE TASK UNLOAD_FACT_BUSTRIP
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from FACT_BUSTRIP table to unload_stage'
AS
COPY INTO @unload_stage/Fact_BusTrip
FROM WAREHOUSE_DB.PUBLIC.FACT_BUSTRIP
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSTYPE
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSTYPE table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusType
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSTYPE
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSROUTE
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSROUTE table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusRoute
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSROUTE
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSINFO
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSINFO table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusInfo
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSINFO
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DE_ROLE;
USE ROLE DE_ROLE;

ALTER TASK TRUNCATE_BUSCALENDAR_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSCALENDAR RESUME;
ALTER TASK add_BusCalendar RESUME;

ALTER TASK TRUNCATE_BUSTYPE_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSTYPE RESUME;
ALTER TASK add_BusType RESUME;

ALTER TASK TRUNCATE_BUSROUTE_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSROUTE RESUME;
ALTER TASK add_BusRoute RESUME;

ALTER TASK TRUNCATE_BUSINFO_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSINFO RESUME;
ALTER TASK add_BusInfo RESUME;

ALTER TASK remove_files_in_upload_stage RESUME;
ALTER TASK TRUNCATE_BUSTRIP_STAGE RESUME;
ALTER TASK LOAD_FACT_BUSTRIP RESUME;
ALTER TASK add_BusTrip RESUME;

ALTER TASK UNLOAD_FACT_BUSTRIP RESUME;
ALTER TASK UNLOAD_DIM_BUSTYPE RESUME;
ALTER TASK UNLOAD_DIM_BUSROUTE RESUME;
ALTER TASK UNLOAD_DIM_BUSINFO RESUME;


