-- Set up Warehouse
CREATE OR REPLACE WAREHOUSE TRANSPORT_WH WITH
WAREHOUSE_SIZE = 'SMALL'
MAX_CLUSTER_COUNT = 2
MIN_CLUSTER_COUNT = 1
AUTO_SUSPEND = 600
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = FALSE
COMMENT = 'This warehouse is used for transportation project demo.';

-- Set up Database for Temporory Tables
CREATE OR REPLACE DATABASE PUBLICTRANSPORTATION;

-- Set up tables for Database PUBLICTRANSPORTATION

CREATE OR REPLACE TABLE BUSTYPE_STAGE
(
	bus_type_id INT NOT NULL,
	bus_type VARCHAR(50) NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE BUSROUTE_STAGE
(
	route_id VARCHAR(50)  NOT NULL,
	route_name VARCHAR(50) NOT NULL,
	depart_address VARCHAR(50) NOT NULL,
  frequency INT NOT NULL,
	operating_start_hour TIME NOT NULL,
  operating_end_hour TIME NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE BUSINFO_STAGE
(
	bus_code VARCHAR(50) NOT NULL,
	seat_capacity INT NOT NULL,
	max_capacity INT NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE BUSCALENDAR_STAGE
(
  date_id VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  week_day VARCHAR(50) NOT NULL,
  day TINYINT NOT NULL,
  month TINYINT NOT NULL,
  year INT NOT NULL
);

CREATE OR REPLACE TABLE BUSTRIP_STAGE
(
  trip_id VARCHAR(50) NOT NULL,
  bus_code VARCHAR(50) NOT NULL,
  route_id VARCHAR(50) NOT NULL,
  bus_type_id INT NOT NULL,
  date_id VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  depart_time TIME NOT NULL,
  arrival_time TIME NOT NULL,
  is_rush_hour VARCHAR(50) NOT NULL,
  real_duration FLOAT NOT NULL,
  standard_duration INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  number_of_busstop INT NOT NULL,
  route_distance FLOAT NOT NULL,
  average_velocity FLOAT NOT NULL,
  number_of_ticket INT NOT NULL,
  fare FLOAT NOT NULL,
  revenue FLOAT NOT NULL,
  modifiled_date DATETIME NOT NULL
);

-- Set up Database for Dimensional Model
CREATE OR REPLACE DATABASE WAREHOUSE_DB;

-- Set up tables for Database WAREHOUSE_DB

CREATE OR REPLACE TABLE DIM_BUSTYPE
(
	bus_type_id INT NOT NULL,
	bus_type VARCHAR(50) NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE DIM_BUSROUTE
(
	route_id VARCHAR(50)  NOT NULL,
	route_name VARCHAR(50) NOT NULL,
	depart_address VARCHAR(50) NOT NULL,
  frequency INT NOT NULL,
	operating_start_hour TIME NOT NULL,
  operating_end_hour TIME NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE DIM_BUSINFO
(
	bus_code VARCHAR(50) NOT NULL,
	seat_capacity INT NOT NULL,
	max_capacity INT NOT NULL,
  modifiled_date DATETIME NOT NULL
);

CREATE OR REPLACE TABLE DIM_BUSCALENDAR
(
  date_id VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  week_day VARCHAR(50) NOT NULL,
  day TINYINT NOT NULL,
  month TINYINT NOT NULL,
  year INT NOT NULL
);

CREATE OR REPLACE TABLE FACT_BUSTRIP
(
  trip_id VARCHAR(50) NOT NULL,
  bus_code VARCHAR(50) NOT NULL,
  route_id VARCHAR(50) NOT NULL,
  bus_type_id INT NOT NULL,
  date_id VARCHAR(50) NOT NULL,
  date DATE NOT NULL,
  depart_time TIME NOT NULL,
  arrival_time TIME NOT NULL,
  is_rush_hour VARCHAR(50) NOT NULL,
  real_duration FLOAT NOT NULL,
  standard_duration INT NOT NULL,
  status VARCHAR(50) NOT NULL,
  number_of_busstop INT NOT NULL,
  route_distance FLOAT NOT NULL,
  average_velocity FLOAT NOT NULL,
  number_of_ticket INT NOT NULL,
  fare FLOAT NOT NULL,
  revenue FLOAT NOT NULL,
  modifiled_date DATETIME NOT NULL
);

-- Create csv file format
CREATE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
DATE_FORMAT = 'YYYY-MM-DD';

-- Create Stages
CREATE STAGE UPLOAD_STAGE
FILE_FORMAT = CSV_FORMAT;

CREATE STAGE UNLOAD_STAGE
FILE_FORMAT = CSV_FORMAT;

-- Create Tasks to load data from stage to tables in PublicTransportation DB
USE ROLE ACCOUNTADMIN;
ALTER ACCOUNT SET TIMEZONE = 'Asia/Ho_Chi_Minh'

--- UPDATE DIM_BUSCALENDAR
CREATE OR REPLACE TASK add_BusCalendar
  WAREHOUSE = TRANSPORT_WH
    SCHEDULE = 'USING CRON 30 15 4 9 * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusCalendar TABLE'
AS
COPY INTO BUSCALENDAR_STAGE
FROM @UPLOAD_STAGE/BusCalendar_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSCALENDAR
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusCalendar
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSCALENDAR
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSCALENDAR_STAGE;

-- Task to truncate stage table BUSCALENDAR_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSCALENDAR_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSCALENDAR
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSCALENDAR_STAGE;

--- UPDATE DIM_BUSTYPE
CREATE OR REPLACE TASK add_BusType
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add Bustype TABLE'
AS  
COPY INTO BUSTYPE_STAGE
FROM @UPLOAD_STAGE/BusType_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSTYPE
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusType
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSTYPE
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSTYPE_STAGE;

-- Task to truncate stage table BUSTYPE_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSTYPE_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSTYPE
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSTYPE_STAGE;

-- UPDATE DIM_BUSROUTE
CREATE OR REPLACE TASK add_BusRoute
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusRoute TABLE'
AS
COPY INTO BUSROUTE_STAGE
FROM @UPLOAD_STAGE/BusRoute_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSROUTE
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusRoute
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSROUTE
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSROUTE_STAGE;

-- Task to truncate stage table BUSROUTE_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSROUTE_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSROUTE
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSROUTE_STAGE;

-- UPDATE DIM_BUSINFO
CREATE OR REPLACE TASK add_BusInfo
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 4 * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusInfo TABLE'
AS
COPY INTO BUSINFO_STAGE
FROM @UPLOAD_STAGE/BusInfo_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_DIM_BUSINFO
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusInfo
AS
  INSERT OVERWRITE INTO WAREHOUSE_DB.PUBLIC.DIM_BUSINFO
  SELECT DISTINCT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSINFO_STAGE;
-- Task to truncate stage table BUSINFO_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSINFO_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_DIM_BUSINFO
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSINFO_STAGE;

-- UPDATE FACT_BUSTRIP
CREATE OR REPLACE TASK add_BusTrip
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 15 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Add BusTrip TABLE'
AS
COPY INTO BUSTRIP_STAGE
FROM @UPLOAD_STAGE/BusTrip_Stage.csv.gz;

CREATE OR REPLACE TASK LOAD_FACT_BUSTRIP
  WAREHOUSE = TRANSPORT_WH
  AFTER add_BusTrip
AS
  INSERT INTO WAREHOUSE_DB.PUBLIC.FACT_BUSTRIP
  SELECT *
  FROM PUBLICTRANSPORTATION.PUBLIC.BUSTRIP_STAGE;

-- Task to truncate stage table BUSTRIP_STAGE
CREATE OR REPLACE TASK TRUNCATE_BUSTRIP_STAGE
  WAREHOUSE = TRANSPORT_WH
  AFTER LOAD_FACT_BUSTRIP
AS
TRUNCATE TABLE PUBLICTRANSPORTATION.PUBLIC.BUSTRIP_STAGE;

CREATE OR REPLACE TASK remove_files_in_upload_stage
  WAREHOUSE = TRANSPORT_WH
  COMMENT = 'Remove files in upload stage'
  AFTER TRUNCATE_BUSTRIP_STAGE
AS
REMOVE @UPLOAD_STAGE;

CREATE OR REPLACE TASK UNLOAD_FACT_BUSTRIP
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from FACT_BUSTRIP table to unload_stage'
AS
COPY INTO @unload_stage/Fact_BusTrip
FROM WAREHOUSE_DB.PUBLIC.FACT_BUSTRIP
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSTYPE
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSTYPE table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusType
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSTYPE
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSROUTE
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSROUTE table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusRoute
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSROUTE
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK UNLOAD_DIM_BUSINFO
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 5 16 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Unload data from DIM_BUSINFO table to unload_stage'
AS
COPY INTO @unload_stage/Dim_BusInfo
FROM WAREHOUSE_DB.PUBLIC.DIM_BUSINFO
FILE_FORMAT = (TYPE='CSV')
HEADER = TRUE
OVERWRITE = TRUE;

CREATE OR REPLACE TASK remove_files_in_unload_stage
  WAREHOUSE = TRANSPORT_WH
  SCHEDULE = 'USING CRON 30 19 * * * Asia/Ho_Chi_Minh'
  COMMENT = 'Remove files in upload stage'
AS
REMOVE @UNLOAD_STAGE;

USE ROLE ACCOUNTADMIN;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DE_ROLE;
USE ROLE DE_ROLE;

ALTER TASK TRUNCATE_BUSCALENDAR_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSCALENDAR RESUME;
ALTER TASK add_BusCalendar RESUME;

ALTER TASK TRUNCATE_BUSTYPE_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSTYPE RESUME;
ALTER TASK add_BusType RESUME;

ALTER TASK TRUNCATE_BUSROUTE_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSROUTE RESUME;
ALTER TASK add_BusRoute RESUME;

ALTER TASK TRUNCATE_BUSINFO_STAGE RESUME;
ALTER TASK LOAD_DIM_BUSINFO RESUME;
ALTER TASK add_BusInfo RESUME;

ALTER TASK remove_files_in_upload_stage RESUME;
ALTER TASK TRUNCATE_BUSTRIP_STAGE RESUME;
ALTER TASK LOAD_FACT_BUSTRIP RESUME;
ALTER TASK add_BusTrip RESUME;

ALTER TASK UNLOAD_FACT_BUSTRIP RESUME;
ALTER TASK UNLOAD_DIM_BUSTYPE RESUME;
ALTER TASK UNLOAD_DIM_BUSROUTE RESUME;
ALTER TASK UNLOAD_DIM_BUSINFO RESUME;

ALTER TASK remove_files_in_unload_stage RESUME;


